services:
  gard-gateway:
    build:
      context: . # Assuming Dockerfile is in the root directory
      dockerfile: ./gateway/Dockerfile
    ports:
      - "8080:8080" # Expose the Go API server on port 8080
    depends_on:
      - ozone
    networks:
      - backend

  ozone:
    image: apache/ozone:1.3.0 # Use the latest stable version of Apache Ozone
    environment:
      - OZONE-SITE.XML_HADOOP_SCM_DATANODE_HTTP_ADDRESS=ozone:9878
    ports:
      - "9878:9878" # Expose Apache Ozone on port 9878
    networks:
      - backend

networks:
  backend:
    driver: bridge
